base:
  project_id : 1
  project: BikeShare
  random_state: 42
  test_size: 0.2

config:
  params: config/params.yaml
  schema_training: config/schema_training.json
  schema_prediction: config/schema_prediction.json

cloud_provider:
  name: microsoft
  is_enabled: 0

data_download:
  cloud_training_directory_path: raw_data/training_batch_files/
  cloud_prediction_directory_path: raw_data/prediction_batch_files/
  no_of_files: 24
  core_data_url: https://s3.amazonaws.com/capitalbikeshare-data/
  weather_data_url:

artifacts:
  training_data:
    good_file_path: artifacts/training_data/Training_Raw_files_validated/Good_raw
    bad_file_path: artifacts/training_data/Training_Raw_files_validated/Bad_raw
    archive_bad_file_path: artifacts/training_data/TrainingArchiveBadData
    training_file_from_db: artifacts/training_data/Training_FileFromDB
    input_csv_day: input_day.csv
    input_csv_hour: input_hour.csv
    null_value_info_file_path:  artifacts/training_data/preprocessing/null_value
    plots: artifacts/training_data/plots
    scaler_path: artifacts/training_data/preprocessing/scaler

  model:
    model_path: artifacts/model


  prediction_data:
    good_file_path: artifacts/prediction_data/Prediction_Raw_files_validated/Good_raw
    bad_file_path: artifacts/prediction_data/Prediction_Raw_files_validated/Bad_raw
    archive_bad_file_path: artifacts/prediction_data/PredictionArchiveBadData
    prediction_file_from_db: artifacts/prediction_data/Prediction_FileFromDB
    input_csv_day: input_day.csv
    input_csv_hour: input_hour.csv
    prediction_output_file_path: artifacts/Prediction_Output_DIR/
    prediction_file_name: Predictions.csv

data_source:
  Training_Batch_Files: Training_Batch_Files
  Prediction_Batch_Files: Prediction_Batch_Files


log_database:
  training_database_name: bikeshare_training
  prediction_database_name: bikeshare_prediction

dataset:
  unwanted_column:
    - ride_id
    - rideable_type
    - start_station_name
    - start_station_id
    - end_station_name
    - end_station_id
    - end_lat
    - end_lng
    - start_lat
    - start_lng
    - started_at
    - ended_at

  convert_to_datetime:
    - started_at

  day:
    categorical:
      - dayofweek
      - holiday
      - day
      - week
      - month
      - season
      - weather_condition
      - windgust_info
      - precipitation_info
    numerical:
      - minTemp
      - maxTemp
      - maxSteadyWind
      - precipitation
      - pressure
    log_transform:
      - maxSteadyWind

  hour:
    categorical:
      - hour
      - dayofweek
      - holiday
      - day
      - week
      - month
      - season
      - icon
      - wind_dir_deg
    numerical:
      - temperature
      - rel_temperature
      - rel_humidity
      - dew_point
      - pressure
      - wind_speed
    log_transform:
      - member_casual
      - wind_speed

  database_detail:
    training_database_name: bikeshare_training
    prediction_database_name: bikeshare_prediction
    dataset_daily_training_collection_name: bikeshare_daily_training_dataset
    dataset_daily_prediction_collection_name: bikeshare_daily_prediction_dataset
    dataset_hourly_training_collection_name: bikeshare_hour_training_dataset
    dataset_hourly_training_collection_name: bikeshare_hour_training_dataset

target_columns:
  columns:
    - member_casual